### ISSUE TITLE
The gem doesn't shout when validations fail, silently ignore the inserts and proceeds

### ISSUE THREAD

**Issue by navneet-flipkart** [zdennis/activerecord-import#110]
Hi,

I noticed this issue with gem 'activerecord-import', '0.3.1'

While running tests over my API seems like the inserts fail silently when I have validations w.r.t. some fields presence.

validates_presence_of :attr1, :attr2

Doesn't the gem throw an error if the above validation fails? ActiveRecord does throw an error in such cases.

**Comment by jkowens** [comment]
The `#import` method returns an object that includes an array of objects that failed validation, so that can be checked to see if any were unsuccessful:

```
result = Post.import posts
if result.failed_instances.any?
   # ...
end
```

As of version 0.13.0 there is also an `#import!` method which will raise an exception if a validation error occurs.  This means that nothing will be inserted if any objects fail validation.
