### ISSUE TITLE
Validations Question

### ISSUE THREAD

**Issue by yskarpathiotis** [zdennis/activerecord-import#117]
Hey,
I have a question about this great gem....

Lets say i have one field named *title* for my model **Book**, and have a uniqueness validator written as such: *validates :title, uniqueness: true*.

If in my import i have two books with the same *title* they will both get imported... the validation seems to be checking the validation against the table before the import command.
If i run the same import again, as expected nothing gets imported because of the validation has recognized that these are all duplicate *titles*.

Is this the expected behavior? And if so, is there a way to get the validations checking against other already imported items from the same import?

Thanks

**Comment by jkowens** [comment]
@yskarpathiotis I know this is an old issue, but yes that is currently the expected behavior.  ActiveRecord uniqueness validations only check the state of the database, not what is included in the import. Keep on eye #228 as that could possibly change.

To protect the integrity of your data, I would suggest adding unique indexes on the database for those columns. That way if the import contained duplicates, the insert would throw an error (or you could make use of the `:on_duplicate_key_update` option for MySQL or PG 9.5+).
