### ISSUE TITLE
import!

### ISSUE THREAD

**Issue by ghazel** [zdennis/activerecord-import#162]
Similar to AR `create!`, it would be nice to have a variant of import, `import!`, which raised a `RecordInvalid` exception if validation errors occurred.

**Comment by mockdeep** [comment]
Indeed. We monkey patched it for ourselves.

**Comment by zdennis** [comment]
@mockdeep, care to share a link to your monkey patch?

**Comment by mockdeep** [comment]
@zdennis it's pretty basic:

```ruby
module ActiveRecord
  class Base
    def self.import!(models)
      result = import(models)

      failed_instances = result.failed_instances
      fail "Invalid #{name}: #{failed_instances}" if failed_instances.any?
    end
  end
end
```

**Comment by roberts1000** [comment]
This would be a very useful feature.  I'm a new user of the gem and I assumed `validate: true` would complain if there validation failures.  A current project I'm developing went several weeks before anyone noticed some critical data wasn't being mass imported by the gem due to validation failures.  `import!` would be a sensible enhancement.  Would a PR on this be accepted?

**Comment by zdennis** [comment]
Yes it would @roberts1000
