### ISSUE TITLE
Private method called when importing has_one relationships

### ISSUE THREAD

**Issue by mbrung** [zdennis/activerecord-import#190]
Consider the following model, with a Question having one Rule:
```ruby
class Question < ActiveRecord::Base
	has_one :rule, autosave: true
end
```
```ruby
class Rule < ActiveRecord::Base
	belongs_to :question
end
```
Calling Question#import (with `recursive: true`) yields the following:
```
<#<NoMethodError: private method `select' called for #<ActiveRecord::Associations::HasOneAssociation:0x007fc26784a658>>>.
```

**Comment by D-side** [comment]
Just bumped into that myself. Wow, this didn't get any attention at all.

I looked through the implementation, it seems to be caused by [this line](https://github.com/zdennis/activerecord-import/blob/master/lib/activerecord-import/import.rb#L453) of `find_associated_objects_for_import`:

```ruby
changed_objects = association.select {|a| a.new_record? || a.changed?}
```

A workaround for users could be to make an identical (except for the name in plural) `has_many` and use that when building data for import. A hack, but might get the code working quickly.

This is really an issue though.

**Comment by zdennis** [comment]
If someone wants to submit a PR with @mbrung's commit/fix I'll be happy to merge it in. Otherwise it'll likely have to wait a few more weeks until I go on holiday.
