### ISSUE TITLE
Add Examples to Readme

### ISSUE THREAD

**Issue by triptec** [zdennis/activerecord-import#229]
It would be nice with some code to go with the example of books, publishers and reviews in the readme.

**Comment by allenwlee** [comment]
agreed; it isn't clear how we are supposed to implement an import with more than one associated model

**Comment by jkowens** [comment]
The [wiki](../wiki) has some examples including one that imports an associated model. I believe the `:recursive` option (import associations) is only available for Postgres, but that isn't specified in the wiki doc.

**Comment by allenwlee** [comment]
yes i added a 'multi-tier' example to the wiki last week and neglected to update this issues thread.  thanks.

**Comment by JHFirestarter** [comment]
@allenwlee what might the 'multi-tier' example syntax be if both `books` and `reviews` tables have multiple attributes? Say the starting data is a csv of reviews with `book`, `author`, and `commentary` columns...and you had Book and Review models (Book `has_many` reviews, Review `belongs_to` book)? The `books` table may have `title` and `author` attributes, while the reviews may have `commentary` and `book_id` (foreign key) attributes.

**Comment by allenwlee** [comment]
@JHFirestarter is `commentary` a separate model or just a column?

**Comment by JHFirestarter** [comment]
@allenwlee correct re: just a column. Apologies, on "line 3" you have the book attributes (`name` and `author`), while in "line 4" you have the review attributes (`title` and `commentary`)? One of my issues was understanding which model's attributes go where.

**Comment by allenwlee** [comment]
yes that is intentional. line three populates a newly instantiated `Book` model.  Line four 'builds' a review model that `belongs_to` that newly instantiated book object.  [Here's](http://stackoverflow.com/questions/783584/ruby-on-rails-how-do-i-use-the-active-record-build-method-in-a-belongs-to-rel) a good explanation of the ActiveRecord `build` method.

**Comment by JHFirestarter** [comment]
Thx. I'll update my comment to match the attributes you have in the example.

**Comment by JHFirestarter** [comment]
@allenwlee Btw, +1 for @triptec 's OP. I think (maybe wrong) a good example would be a gist with models and similar example .rb using books, publishers & reviews, where there's need for a bulk action with associations in an app that relies on those associations in its views. Instead of values like "John Smith," one would have to work with a variable of some sort before import. 

If source data is commonly in some type of excel file, would the best example include converting that to an array of arrays (or array of hashes)? How does one refactor for an array of arrays (or array of hashes) instead of "John Smith?"

The reason for the question is reading other issues, it seems there's no solid example that includes the things you found (like the need for `autosave: true`? for `inverse_of`?)

Here's my attempt, which fails to accomplish the goal, as (while it does import to 3 tables quickly) it does **not** populate the foreign keys `publisher_id` or `book_id` in the reviews table, assuming that there are `has_many` and `belongs_to` associations. The below also touches on how to combine roo with ar-import. Starting with a 4-column xlsx file:

    require 'roo'
    require 'activerecort-import'

    xlsx = Roo::Excelx.new(relative_file_path)
    xlsx.default_sheet = xlsx.sheets[1] # sets second sheet
    first = 5 # in the event headers are further down the file on say row 4 (so values are 4+1)
    last = xlsx.last_row # if unknowable number of rows bc starting file may change
  
    # AR table columns
    bk_col = [:title, :author]
    rev_col = [:review]
    pub_col = [:publisher]

    # values to import
    bks = []
    revs = []
    pubs = []

    first.upto(last) do |row|
      title = xlsx.cell(row, 1)
      auth = xlsx.cell(row, 2)
      pub = xlsx.cell(row, 3)
      rev = xlsx.cell(row, 4)

      books << [title, auth]
      reviews << [rev]
      publisher << [pub]
    end
		
    Book.import bk_col, bks, :validate => false # for speed
    Review.import rev_col, revs, :validate => false
    Publisher.import pub_col, pubs, :validate => false

It **seems** that perhaps the reviews and publishers importing above may be redundant (and counterproductive) if associations are setup well and .build is used--but I do not know how to extrapolate from your example. I'm sure there's a much better way than I'm attempting...but after days (weeks) on stack overflow and reading ar-import lib/ etc, I would think this kind of example is very common and useful to others if done correctly. Simply adding `:recursive => true` as an import option above does not do the trick (each error).

**Comment by allenwlee** [comment]
OK, i don't know what the association is between books and publishers.  unless it is Book `has_one` or `has_many` Publisher (which I doubt), then it is true in this example that you can't import books and publishers all in one import function.  you can however import books and reviews in one go:

e.g.:
```
books=[]
first.upto(last) do |row|
  title = xlsx.cell(row, 1)
  auth = xlsx.cell(row, 2)
  pub = xlsx.cell(row, 3)
  rev = xlsx.cell(row, 4)
  book = Book.new(title: title, auth: auth)
  book.reviews.build(comment: rev)
  books << book
end

Book.import books
```

**Comment by JHFirestarter** [comment]
True (was trying to keep with README). Better example would be critics instead of publishers. Books and Critics would have has_many .. through reviews associations. Still, this is quite helpful. Do the models need autosave: true, etc?

**Comment by JHFirestarter** [comment]
Update: tried importing Critics a few ways to no avail (e.g. 
    
    books = []
    ...
      book = Book.new(title: title, author: auth)
      book.critics.build(name: critic) # `has_many .. through .. reviews` association
      book.reviews.build(review: rev)
      books << book
    end

starts to create books in one big motion, but then it yields `NoMethodError: undefined method critic_id=' for #<Critic:0x007fd244263158>`)

**Comment by oniofchaos** [comment]
With what's in the README [here](https://github.com/zdennis/activerecord-import#examples) now, is this still needed @jkowens ?

**Comment by jkowens** [comment]
I think we can go ahead and close this issue.
