### ISSUE TITLE
On duplicate key not updating has_many association

### ISSUE THREAD

**Issue by binarymason** [zdennis/activerecord-import#323]
```ruby
first_book = Book.new(name: "book 1")
first_book.reviews.build(title: "Cool")
first_book.save!

books = []
10.times do |i|
  book = Book.new(name: "book #{i}")
  book.reviews.build(title: "Excellent")
  books << book
end
Book.import books, recursive: true, on_duplicate_key_update: {
  conflict_target: [:name],
  columns:         [:reviews] # this doesn't work and will error out
}

Book.find_by_name("book 1").reviews # => [ #Review:0x007f9639949068 title: "Cool" ]
```

How to update `has_many` association on duplicate key?  Expected behavior is this:

```ruby
Book.find_by_name("book 1").reviews # => [ #Review:0x007f9639949068 title: "Excellent" ]
```

**Comment by jkowens** [comment]
As long as there isn't a chance of a duplicate key exception for the associations, you can do a recursive import with on_duplicate_key_update specified for the parent model, otherwise recursive import will not work in that scenario. More than likely you won't want to use the recursive option, and instead just import the parent and association separately.

The sample code above isn't quite right. The column you specified to be updated on duplicate key isn't an actual column in the books table.

```
Book.import books, recursive: true, on_duplicate_key_update: {
  conflict_target: [:name],
  columns:         [:updated_at] # revised to a column in the books table
}
```

I would probably suggest something like this if there is a chance that books have reviews that already exist:

```
Book.import books, on_duplicate_key_update: {
  conflict_target: [:name],
  columns: [:updated_at] 
}

reviews = books.map(&:reviews).flatten
Review.import reviews, on_duplicate_key_update: { ... }
```
Hopefully that works, just thinking off the top of my head right now.

**Comment by bswinnerton** [comment]
👋 @jkowens,

Sorry to comment on a closed thread, but I'm having a similar problem and I think the context in this issue is valuable.

In your [example above](https://github.com/zdennis/activerecord-import/issues/323#issuecomment-252082341), you suggest:

```ruby
Book.import books, on_duplicate_key_update: {
  conflict_target: [:name],
  columns: [:updated_at] 
}

reviews = books.map(&:reviews).flatten
Review.import reviews, on_duplicate_key_update: { ... }
```

But in that scenario, `books.map(&:reviews).flatten` wouldn't have persisted `books`, which would mean that each of the `reviews` that are being imported would have a `book_id` of `nil`. Is there any way that you can think of to get around that? Perhaps is it possible to pass some sort of argument for `Book.import` to mutate the `books` array with _persisted_ books?

**Comment by jkowens** [comment]
@bswinnerton hello thanks for using activerecord-import!

So I do see one thing that should be corrected in that example:

```
Book.import books, on_duplicate_key_update: {
  conflict_target: [:name],
  columns: [:updated_at] 
},
validate: false
```

We want to skip validations to make sure all books are inserted or updated.  This example was specific to Postgresql which allows ar-import to set the ids on inserted and updated models.  That means that all reviews for each book should have the `book_id` value set. This does not happen for MySQL.

**Comment by maximbond** [comment]
Smth like this should also work:

```ruby
books = []
10.times do |i|
  book = Book.find_or_initialize_by(name: "book #{i}")
  book.reviews.find_or_initialize_by(title: "Excellent")
  books << book
end
Book.import books, validate: false, recursive: true, on_duplicate_key_update: {
  columns: Book.column_names - %w(id created_at updated_at)
}
```
