### ISSUE TITLE
Release version 0.16.0

### ISSUE THREAD

**Issue by jkowens** [zdennis/activerecord-import#325]
`master` includes the following updates:

https://github.com/zdennis/activerecord-import/pull/305
https://github.com/zdennis/activerecord-import/pull/309
https://github.com/zdennis/activerecord-import/pull/312
https://github.com/zdennis/activerecord-import/pull/314
https://github.com/zdennis/activerecord-import/pull/315
https://github.com/zdennis/activerecord-import/pull/322
 https://github.com/zdennis/activerecord-import/pull/324
https://github.com/zdennis/activerecord-import/pull/326

@zdennis is there anything more I should to in preparation for a new release?

**Comment by zdennis** [comment]
@jkowens, most recently I've created a release branch then:

* update the `CHANGELOG` in a commit
* update the version in `lib/activerecord-import/version.rb` in a commit
* merge into master
* tag release (loosely sem-ver)
* push tags
* `gem build *.gemspec`
* `gem push pkg/...`

For the `gem push` I'll need to add you as an owner on rubygems. If you want to send me your ruby gems email I'll get you added. 

If you're good to do this release I'll take what we learn and put together a `RELEASE` readme. I'm happy to change/automate any part of this. It's so basic because it's just been me doing it for the past 10 years. :)

If any questions don't hesitate to let me know. Thanks @jkowens !

**Comment by jkowens** [comment]
Cool, that's not too bad 😄  I'm jkowens at gmail.com.

**Comment by zdennis** [comment]
You've been added!

**Comment by jkowens** [comment]
Well, I've pushed a new release...hope all is good 😅  🙏  

Your instructions were great btw 👍

**Comment by zdennis** [comment]
:boom: there it is:

```
> gem search -r activerecord-import

*** REMOTE GEMS ***

activerecord-import (0.16.0)
```

Almost forgot, one last thing I usually do is comment on the issues/PRs that were a part of the release and let them know the fix is out in the x.x.x version.

Thanks for releasing!
