### ISSUE TITLE
Naming and file structure

### ISSUE THREAD

**Issue by ioquatix** [zdennis/activerecord-import#347]
Have you considered copying the active_record naming convention of the file structure? This would improve consistency.

e.g.

```ruby
require 'active_record/import'
```

**Comment by jkowens** [comment]
That sounds like a nice idea, I'm not sure what all impact that would have. I guessing it's probably a little more complicated than it sounds. @zdennis do you have any thoughts on this one?

**Comment by zdennis** [comment]
@jkowens / ioquatix, I was trying to not be presumptuous about what files they may add in the future to their project directory and since this project is not a part of `active_record` officially I wanted to respectful of code/project ownership boundaries to avoid unnecessary conflicts down the road.

I'm happy to discuss further if you have any other thoughts or ideas.

**Comment by ioquatix** [comment]
Good points. I'd just say that the principle of least surprise applies here, and it's also about consistency. You are right it might break in the future but the very nature of this gem could break with any update to AR anyway. I decided to call my gems active_record/migrations and active_record/rack and they feel like they integrate well

**Comment by jkowens** [comment]
When it comes to potential conflicts, I think the concern would mostly be around namespace collisions (module names) not so much file structure / file names. I could see this being a nice update at some point and it might be good to keep in mind if any future refactoring is planned 😄

**Comment by ioquatix** [comment]
Yeah totally understand where you are coming from. Thanks so much for your consideration and good luck making the right decision :)
