### ISSUE TITLE
Gemfile order with composite_primary_keys gem

### ISSUE THREAD

**Issue by dukedave** [zdennis/activerecord-import#396]
This `Gemfile` snippet:

```
gem 'activerecord-import', '~> 0.17'
gem 'composite_primary_keys', '~> 8.x'
```

Causes:

```
undefined method `import' for #<Class:0x0055aba6b9b110>
```

However, if I flip the `gem` lines around:

```
gem 'composite_primary_keys', '~> 8.x'
gem 'activerecord-import', '~> 0.17'
```

Then `import` works correctly.

I don't know if this is expected behavior, but it'd be nice to put in the readme if it is.

This appears unrelated to  #111.

**Comment by jkowens** [comment]
This wasn't something I expected, but looking through the composite_primary_keys source code it looks like it monkey patches the ActiveRecord::Base.establish_connection method as well (at least version 8.x does). My guess is that when it's loaded after activerecord-import it trashes our method definition.

It looks like starting with composite_primary_keys 9.0.5 they changed the way they handle database connections, so it might not be an issue for projects using ActiveRecord 5. It would be nice if this is something that could be fixed in the composite_primary_keys project, but I would happily accept a PR to document this behavior. Thanks!

**Comment by jkowens** [comment]
Hey @codeodor, I see you are a composite_primary_keys contributor. Could you confirm (or deny) my suspicions here 😄

**Comment by jkowens** [comment]
Thanks @codeodor! Ok sounds like some documentation for using the two gems together would be a good idea in this project's readme.

**Comment by oniofchaos** [comment]
@dukedave I realize this is pretty old and I'm not sure if this is still a problem for you anymore. If it is, would you be able to provide a sample project that demonstrates the error?

**Comment by dukedave** [comment]
@oniofchaos as far as I can remember it wasn't a problem so long as we kept the order flipped around in the `Gemfile`.

I'm afraid I no longer work on the project which used the gem.

**Comment by oniofchaos** [comment]
That's fair. Do you think it makes sense to close the issue to keep the issue list clean?

**Comment by dukedave** [comment]
Deal :+1:
