### ISSUE TITLE
Is 'after_initialize' not considered a 'normal' callback? How can I disable it?

### ISSUE THREAD

**Issue by gregblass** [zdennis/activerecord-import#399]
I thought all callbacks would be disabled, but it looks like after_initialize is not. How would I go about disabling that on an import? I'm using the style like:

```
customers = []

Legacy::LegacyCustomer.find_each(batch_size: 1000) do |legacy_customer|
 customers << Customer.new(
    id: legacy_customer.id,
    ... # => More attributes here
  )
end

Customer.import customers, validate: false
```

**Comment by jkowens** [comment]
If you need to avoid that callback I would suggest trying to import either an array of hashes or an array of columns and values instead of instantiating ActiveRecord objects. This should work since you have specified `validate: false` and it won't initialize the ActiveRecord models.

Here are some examples for using those:

https://github.com/zdennis/activerecord-import/wiki/Examples

If you want to try disabling that callback here is a block that might help:

http://thelazylog.com/skip-activerecord-callbacks/

**Comment by jkowens** [comment]
Btw I've updated the wiki entry on callbacks to clarify which ones do not run on import:

https://github.com/zdennis/activerecord-import/wiki/Callbacks

**Comment by jkowens** [comment]
Just to give a quick example of using hash objects for import:

```
customers = []

Legacy::LegacyCustomer.find_each(batch_size: 1000) do |legacy_customer|
 customers << {
    id: legacy_customer.id,
    ... # => More attributes here
 }
end

Customer.import customers, validate: false
```

**Comment by gregblass** [comment]
Thank you @jkowens!
