### ISSUE TITLE
0.18.2 does not set @new_record to false

### ISSUE THREAD

**Issue by nijikon** [zdennis/activerecord-import#415]
With [this](https://github.com/zdennis/activerecord-import/compare/v0.18.1...v0.18.2#diff-70d0c2152cc72037bcf5c177f03eb9f8R524) change `@new_record` [flag](https://github.com/zdennis/activerecord-import/blob/master/lib/activerecord-import/import.rb#L654) after import is not being set to false. That means unless you run `reload` on your model `persisted?` method will return false.

I execute import this way. Maybe I'm doing it wrong 😺 

```ruby
@klass.import(
  attributes,
  resources,
  validate: @validate,
  on_duplicate_key_ignore: true
)
```

**Comment by jkowens** [comment]
Hi @nijikon, yes as of v0.18.2 the imported models won't have their IDs set when using the option `:on_duplicate_key_ignore`. The reason is that Postgres doesn't return an ID for duplicate keys, so that meant we were possibly setting an ID on the incorrect model. 

See: https://github.com/zdennis/activerecord-import/issues/411

There doesn't seem to be a good work around for this...so that is unfortunately one of the trade offs using this option.

**Comment by nijikon** [comment]
@jkowens What I forgot to mention is that we pass the ids. So if I'm not mistaken in that case it should trigger that regardless `:on_duplicate_key_ignore` option.

**Comment by mensfeld** [comment]
We use uuids (under id key) so we always know our ids on insert

**Comment by jkowens** [comment]
That's a scenario I didn't consider. I'll see what I can come up with for a fix. Thanks!

**Comment by mensfeld** [comment]
@jkowens we've knew about postgres not returning stuff on ignore and that's exactly the reason why we've taken the uuid autogenerated route :) - thank you for your help!

**Comment by jkowens** [comment]
I just merged a possible fix into master. Can you give that a spin and let me know if it works as you expect? If so, I'll cut another release.

**Comment by nijikon** [comment]
@jkowens That was quick! I can confirm that our specs pass with the version from master! 🎉

**Comment by jkowens** [comment]
I just release v0.18.3 with this update. Thanks again 👍
