### ISSUE TITLE
Document lack of uniqueness validation

### ISSUE THREAD

**Issue by xruins** [zdennis/activerecord-import#430]
Even `validate: true` was set for `import` method,
ActiveRecord::Validations::UniquenessValidator will be disabled by the code on https://github.com/zdennis/activerecord-import/blob/master/lib/activerecord-import/import.rb#L42 .

Since it's confusable without an annotation, I prefer this incompatibility is mentioned in some document.

**Comment by jkowens** [comment]
Good idea. The history of why uniqueness validation is avoided is found here: https://github.com/zdennis/activerecord-import/issues/228.

**Comment by xRuins** [comment]
Thanks! :)

**Comment by jkowens** [comment]
An option `validate_uniqueness` has been added in v0.27.0 that allows users to enable uniqueness validation:

```
Book.import books, validate_uniqueness: true
```
This is not a recommended approach as it has several potential issues, so user beware ☠️

**Comment by oniofchaos** [comment]
It seems like instead of adding documentation around an option that doesn't do anything, the better approach would be to get rid of the option?

**Comment by jkowens** [comment]
@oniofchaos we had completely removed uniqueness validation, but with v0.27.0 we added an option to enable it. By default validating an import will not validate uniqueness. The option `validate_uniqueness` must be set to true for it to happen. So that's really what needs documented now, the default behavior and the special option.

**Comment by xruins** [comment]
Thanks a lot!

**Comment by khalilgharbaoui** [comment]
I know this issue is closed but there is an unanswered question here:

does `validate_uniqueness: true` work independently from `validate: true`?

If `yes` maybe we need it in the docs if `no` we also need it in the docs
This is otherwise confusing and a pain even on and beyond 04-12-219

**Comment by jkowens** [comment]
`validate_uniqueness` takes affect only when `validate: true`. It does not work independently. A PR to document this is welcome. Thanks!

**Comment by khalilgharbaoui** [comment]
@jkowens are you 100% sure that it only takes effect when `validate: true` because I tried it in addition to `validate: false` and it does trigger the uniqueness validations on my model.
Does that mean it also activates and sets `validate: true` even if you explicitly set `validate: false`.

I have finally given up and used a database constraint instead. The above is very unreliable.
At least the database constraint will always raise an error.
https://stackoverflow.com/a/59153244/5641227

**Comment by jkowens** [comment]
@khalilgharbaoui looking at the code I'm not sure how that would be happening. The database constraint approach is the recommended way. Can you post an example of how you were running the import with `validate: false` and `validate_uniqueness: true`?
