### ISSUE TITLE
before_save, before_create, before_update

### ISSUE THREAD

**Issue by indigoviolet** [zdennis/activerecord-import#442]
My reading of the code is that importing with validation will run the `before_validation` and `validate` callbacks, but not the `before_save` and `before_create` (or `before_update`) callbacks before saving.

On the other hand, the approach in https://github.com/zdennis/activerecord-import/wiki/Callbacks will run the `before_save` and `before_create` callbacks before the validations, which isn't as expected either (http://api.rubyonrails.org/classes/ActiveRecord/Callbacks.html)

Is there a reason why this is so, or am I misreading the code?

**Comment by jkowens** [comment]
What you have stated is completely correct. Because activerecord-import has made use of built in validations to validate records, it got the before/after validation callbacks for free. It's a little more complex now the way validations are implemented, but we tried not to change existing behavior.

You're correct too that the recommendation for `before_save` and `before_create` callbacks isn't exactly sound when combining with the validate option. I am coming more to the mindset that I'd rather see this library do less 😝  So I would possibly recommend users do validation on their models and run callbacks before doing the import:

```
books.each do |book|
  if book.valid?
    book.run_callbacks(:save) { false }
    book.run_callbacks(:create) { false }
  end
end
Book.import(books, validate: true)
```

I suppose we could consider a PR to add running those callbacks as an option if there is a compelling need.

**Comment by oniofchaos** [comment]
@jkowens I see you flagged this as docs, where would be the right place to update to see this documented in the project?

**Comment by jkowens** [comment]
@oniofchaos I would love to see the Readme get a full revamp and all of these issues I've flagged as docs I think would be good to include.
