### ISSUE TITLE
Only updating updated_at when the row has changed when using on_duplicate_key_update

### ISSUE THREAD

**Issue by naiyt** [zdennis/activerecord-import#452]
I have a scenario where I essentially need to implement an `after_update` callback on records I'm importing with `activerecord-import`. This is an expensive callback that requires a network request, so I only want it called on records that have been modified as of the latest import. (The data comes over as a CSV that I'm parsing, and it always contains all records, which I don't have control over.) However, it seems like `activerecord-import` always updates the `updated_at` column even when no changes have occurred.

I'm using Postgres 9.6.2. I'm not too familiar with how `ON DUPLICATE KEY UPDATE` works so maybe it's not even possible to do what I'm trying.

Essentially I want to do:

```ruby
import_started_at = Time.now

Thing.import(column_names, rows, on_duplicate_key_update: {
  conflict_target: :id,
  columns: column_names
})

Thing.where("updated_at >= ?", import_started_at).each(&:expensive_network_request)
```

Right now `expensive_network_request` gets called on all records that were imported, even if there wasn't actually a change, because every row gets a new `updated_at`.

Is there a way to do this with the `activerecord-import` gem? I realize that it might just be Postgres that prevents that from easily happening.

**Comment by jkowens** [comment]
The on_duplicate_key_update option is using PostgreSQL's `ON CONFLICT DO UPDATE` (UPSERT) feature under the covers. Technically this is updating every record that is part of the insert (even if it is using the same values) so it is appropriate that `updated_at` is changed.

Are you using this method because the existing data may have been updated? Or could you possibly make use of the on_duplicate_key_ignore option instead? That would only insert new records.

That said, there might be a way to solve the problem you have stated--using the index_predicate portion of the ON CONFLICT DO UPDATE statement:

```
Thing.import(column_names, rows, on_duplicate_key_update: {
  conflict_target: :id,
  index_predicate: '(things.column1, things.column2, ...) is distinct from (excluded.column1, excluded.column2, ...)',
  columns: column_names
})
```
Granted, it is going to be verbose if you have a number of columns you update on a duplicate key conflict, but I think it might work. Also keep in mind, if import with AR models, using an index predicate will prevent activerecord-import from setting IDs or RETURNING values on the models (since the number of returned values won't match the number of models).

See: 

https://stackoverflow.com/questions/41482441/postgresql-upsert-do-nothing-if-fields-dont-change

and:

https://www.postgresql.org/docs/9.5/static/sql-insert.html

Let me know how this goes, I'm curious to hear if this does work out.

**Comment by naiyt** [comment]
Thanks for the reply @jkowens. 

> Are you using this method because the existing data may have been updated?

Yeah, the data dump I'm dealing with can have all records, including new, updated, and unchanged records. So I want to be able to figure out after the fact which records were new or updated and which were unchanged from the last import.

Thanks for the `index_predicate` tip! I'll give it a try a bit later and report back.

**Comment by naiyt** [comment]
So the `index_predicate` was giving me various issues. (Specifically it seems to not have access to the `EXCLUDED` table, although I could have just been doing it wrong.) I tried out the `condition` option instead, though, and it seems to work! (That looks to generate SQL that more closely matches the SO answer you posted.)

Right now my code looks something like this:

```ruby
def self.perform_import(klass, columns, rows, conflict_target)
  return if rows.length == 0
  columns = columns.dup
  klass.import(columns, rows, validate: false, on_duplicate_key_update: {
    conflict_target: conflict_target,
    condition: condition_sql(klass, columns),
    columns: columns
  })
end

def self.condition_sql(klass, columns)
  columns_str = columns.map { |c| "#{klass.quoted_table_name}.#{c}" }.join(", ")
  excluded_str = columns.map { |c| "EXCLUDED.#{c}" }.join(", ")
  "(#{columns_str}) IS DISTINCT FROM (#{excluded_str})"
end
```

From some initial testing this seems to do exactly what I need for new records, updating existing records, and not touching unchanged records.

I'll close this issue, but I'll comment if I find any problems with this solution in case anybody else ends up here. :)

**Comment by jkowens** [comment]
Oops yes, you're right `:condition` is the correct argument to use! That's really cool to hear that it looks to be working 👍
