### ISSUE TITLE
Is it possible to get list of ignored rows which failed foreign key db constraint with ignore: true option?

### ISSUE THREAD

**Issue by rahulwadi** [zdennis/activerecord-import#486]
Model A, Model B & Model C. C belongs to both A & B and has foreign key db constraint on model A & B. 

`result = C.import rows, validate: false, ignore: true 
`

Would it be possible to get list of rows which wasn't imported as a result of failure of foreign key constraints.

Let me know if this is not the right place to ask this question. We can move this thread to StackOverflow.

**Comment by jkowens** [comment]
Unfortunately, I don't think there is anyway to determine which records failed to insert let alone determine if it was due to a failed foreign key constraint just based on what information is returned by the database after the insert.

You could possibly try to query the newly inserted rows and then do some processing to figure what data failed to insert and then go from there. I would say try your hand at StackOverflow and maybe you'll get some good tips. Thanks for using activerecord-import!
