### ISSUE TITLE
values_sql_for_columns_and_attributes doesn't quote properly

### ISSUE THREAD

**Issue by kwasimensah** [zdennis/activerecord-import#501]
There's no branch in values_sql_for_columns_and_attributes that seems to call ActiveRecord::Base.connection.quote, so strings aren't escaped properly when writing to the database. 

I'm working around this by wrapping my strings in a class that implements to_sql to work around it.

**Comment by kwasimensah** [comment]
Also, Ruby 2.4.3

**Comment by jkowens** [comment]
What version of ActiveRecord are you using? Can you provide a script that demonstrates the issue?

**Comment by kwasimensah** [comment]
activerecord-5.1.4. I'm not sure what the best way of setting up a test project with all the rigamarole involved, but try to insert a string that ends with a back slash ("hello world\")

**Comment by jkowens** [comment]
I'm not seeing any issues in my testing. Can you provide a code snippet and the resulting value inserted into the database?

**Comment by kwasimensah** [comment]
Is there a equivalent to to_sql for import?

**Comment by jkowens** [comment]
Unfortunately, no.  Are you able to see the SQL in the log or STDOUT?

**Comment by jkowens** [comment]
Btw I'm still seeing strings like `"'hello world\'" ` handled properly.

**Comment by zdennis** [comment]
@kwasimensah wrote:

> try to insert a string that ends with a back slash ("hello world\") 
> ...
>  d'oh sorry. the String was "'hello world\'" (note the single quotes inside the double quotes.

Are you saying that the string itself contains a double quote, followed by a single quote, followed by hello world, followed by a literal backslash, followed by a single quote, followed by a double quote?

Or, are you saying that in Ruby, your string contains a single quote, followed by hello world, followed by a literal backslash, followed by a single quote?

I am asking for clarification because in when you use a single backslash inside of double quotes it will be used to escape the following character (or it will represent an escape sequence). It does not represent a literal backslash (you need two of backslashes to represent a literal backslash inside of a double-quoted string).

For example, in `irb`:

```ruby
>>puts "'hello world\'"
'hello world'  
>>puts "'hello world\\'"
'hello world\'
```

I hope this doesn't make matters worse, but it's hard to tell what you're expecting to see in the DB and what is being imported. Can you provide more clarity or information?

**Comment by kwasimensah** [comment]
I've rearragend my code sense filing this which is why I seem a little reticent about setting up the exact situation again. 

I had a column of tsvector which I was trying to import using "'hello':1 'world':2" syntax. It turned out one of the words I was importing ending with a slash. So the raw string I tried to insert into the database is "'hello':1 'world\':2"

Since quote function was never called the single quote was interpreted as part of the string. In general though, the fact that  ActiveRecord import doesn't seem to connection.quote the values passed to it seems to be asking for sql injection issues.

**Comment by jkowens** [comment]
`ar-import` absolutely quotes values before inserting into the database:

https://github.com/zdennis/activerecord-import/blob/master/lib/activerecord-import/import.rb#L862-L875

**Comment by jkowens** [comment]
If you quote `"'hello':1 'world\':2"` you will get `"'''hello'':1 ''world'':2'"` because the `\` is interpreted as an escape character. This sounds like the behavior you were seeing, which is correct.

**Comment by kwasimensah** [comment]
Sorry for the confusion then. I think I just misread it. I'll reopen if i see this again.
