### ISSUE TITLE
Ignores primary key unique constraint and creating records with different id

### ISSUE THREAD

**Issue by ganapathy-outstrip** [zdennis/activerecord-import#536]
I am using this gem version `0.25.0` of activerecord-import with PostgreSQL as my db,

When a model have no other unique constraint other than primary key unique, try to call import on that model with active record objects mixed with existing records like this

```ruby
ExampleModel.import([ExampleModel.new, ExampleModel.last])
```
Returning `ActiveRecord::Import::Result` object with a failed instance of `Example.new` and creating a new record in db with the attributes of `ExampleModel.last` record.

The expected behaviour is to return with `ActiveRecord::RecordNotUnique: PG::UniqueViolation: ERROR` but its not.

Even tried this with `On Duplicate Key Update` and expected that the record to be updated (If modified column values supplied), but again new record gets created

```ruby
ExampleModel.import([ExampleModel.new, ExampleModel.last], on_duplicate_key_update: {conflict_target: [:id], columns: [:some_column]})
```

Please let me know if i am missing something, thanks

PS: I am using UUID as my primary key for tables

**Comment by jkowens** [comment]
Using psql can you provide the table definition for `example_models`:

```
\d example_models
```

**Comment by ganapathy-outstrip** [comment]
![image](https://user-images.githubusercontent.com/41161859/42921576-4e2d0778-8b3a-11e8-8bf3-eba45f49bb0d.png)

Please see the screenshot to get table definition.

**Comment by jkowens** [comment]
Thanks, so when `ExampleModel.last` is inserted is it being giving a new id value or is it duplicating another id value in the table?

**Comment by ganapathy-outstrip** [comment]
It is inserting record with new id

**Comment by jkowens** [comment]
Ok, I see what the issue is now. There are some limitations when working with uuid primary keys that your example demonstrates. Currently, new models and existing models cannot be mixed. The reason being if you include the primary key column name in the generated insert statement with a nil value, it just insert nil instead of running the gen_random_uuid() function. However if you don't include the primary key column, you cannot update existing rows because a new uuid primary key will be generated.

Try this and see what happens:

```
ExampleModel.import([ExampleModel.last, ExampleModel.new])
```
You should see an `ActiveRecord::RecordNotUnique` error raised. AR-Import looks at the first model to determine if a primary key column should be included in the insert statement or not.

**Comment by jkowens** [comment]
If you try:

```
ExampleModel.import([ExampleModel.last, ExampleModel.new], on_duplicate_key_update: [:updated_at]
```
I believe you will see both records inserted, but the new one will have a null id.

**Comment by ganapathy-outstrip** [comment]
@jkowens Thanks for the info and clarifying that we can't mix records and how the internal logic works.
I have tried what you gave and saw errors raised, so I have to make two calls to import new and existing records.
I am closing this now but can i know in future is there any plans on mixing records in a single call like this.
