### ISSUE TITLE
Mysql update is not triggering validations

### ISSUE THREAD

**Issue by vision2910** [zdennis/activerecord-import#683]
1. [import_with_validations](https://rubydoc.info/gems/activerecord-import/ActiveRecord/Base#import_with_validations-class_method) is not triggerring active record validations
```
response = User.import_with_validations(columns, values, on_duplicate_key_update: [:role])

D, [2020-06-23T09:02:36.561737 #4366] DEBUG -- :   User Create Many Without Validations Or Callbacks (2.7ms)  INSERT INTO `users` (`id`,`role`) VALUES (701453,'admin'),(701454,'supervisor') ON DUPLICATE KEY UPDATE `users`.`role`=VALUES(`role`)
=> #<struct ActiveRecord::Import::Result failed_instances=[], num_inserts=1, ids=[], results=[]>
```
2. [ActiveRecord Object](https://github.com/zdennis/activerecord-import#activerecord-models) update is also not triggering validations
```
u = User.limit 2
u.map{|i| i.role = 'guest'}
response = User.import(u.to_a, validate: true, on_duplicate_key_update: [:role])
D, [2020-06-24T05:39:58.816201 #3202] DEBUG -- :   User Create Many Without Validations Or Callbacks (3.0ms)  INSERT INTO `users`
.
.
=> #<struct ActiveRecord::Import::Result failed_instances=[], num_inserts=1, ids=[], results=[]>

**Comment by jkowens** [comment]
Are you saying the validations aren't being triggered because you see the message `User Create Many Without Validations Or Callbacks`? That debug message is misleading, it does the validation before that is printed.

As far as `import_with_validations` that is really an internal method, it takes a block that actually does the validating. It shouldn't be used, just use the `import` method.

**Comment by vision2910** [comment]
@jkowens thanks for the prompt response and clarifying about validation. I have verified, it is working now.

Have a good time, cheers!!
